# macOS 系统语义色值
COLOR_PRIMARY_BG = "#FFFFFF"
COLOR_SECONDARY_BG = "#F5F5F7"
COLOR_PRIMARY_TEXT = "#1D1D1F"
COLOR_SECONDARY_TEXT = "#86868B"
COLOR_ACCENT = "#007AFF"
COLOR_SUCCESS = "#34C759"
COLOR_WARNING = "#FF9500"
COLOR_ERROR = "#FF3B30"
COLOR_BORDER = "#D2D2D7"

# 间距（px）
SPACING_BASE = 8
SPACING_PADDING = 8
SPACING_SECTION = 16
SPACING_CONTENT_MARGIN = 20
SPACING_WIDGET = 8
SPACING_FORM_ITEM = 12

# 字体大小（pt）
FONT_TITLE = 13
FONT_SECTION_TITLE = 12
FONT_BODY = 12
FONT_AUXILIARY = 11

# 窗口尺寸
WINDOW_MIN_WIDTH = 640
WINDOW_MIN_HEIGHT = 480
PANEL_DEFAULT_WIDTH = 240
PANEL_MIN_WIDTH = 200
