COLOR_PRIMARY_BG = "#FFFFFF"
COLOR_SECONDARY_BG = "#F5F5F7"
COLOR_PRIMARY_TEXT = "#1D1D1F"
COLOR_SECONDARY_TEXT = "#86868B"
COLOR_TERTIARY_TEXT = "#AEAEB2"
COLOR_ACCENT = "#007AFF"
COLOR_ACCENT_HOVER = "#0066D6"
COLOR_ACCENT_PRESSED = "#0055BB"
COLOR_ACCENT_DISABLED = "#99CCFF"
COLOR_SUCCESS = "#34C759"
COLOR_SUCCESS_BG = "#F0FFF4"
COLOR_WARNING = "#FF9500"
COLOR_ERROR = "#FF3B30"
COLOR_ERROR_BG = "#FFF5F5"
COLOR_BORDER = "#D2D2D7"
COLOR_BORDER_FOCUS = "#007AFF"
COLOR_DIVIDER = "#E8E8ED"
COLOR_INPUT_BG = "#FAFAFA"

SPACING_BASE = 8
SPACING_XS = 4
SPACING_SM = 8
SPACING_MD = 12
SPACING_LG = 16
SPACING_XL = 20
SPACING_XXL = 24
SPACING_FORM_ITEM = 10
SPACING_SECTION = 20
SPACING_CONTENT_MARGIN = 16
SPACING_WIDGET = 8
SPACING_SECTION_TITLE_TOP = 12
SPACING_SECTION_TITLE_BOTTOM = 4

FONT_TITLE = 15
FONT_SECTION_TITLE = 12
FONT_BODY = 12
FONT_LABEL = 11
FONT_AUXILIARY = 10
FONT_BUTTON = 12
FONT_INPUT = 12

WEIGHT_BOLD = "bold"
WEIGHT_MEDIUM = "500"
WEIGHT_NORMAL = "normal"

RADIUS_SM = 4
RADIUS_MD = 6
RADIUS_LG = 8
RADIUS_XL = 12

INPUT_HEIGHT = 32
BUTTON_HEIGHT = 36
BUTTON_HEIGHT_SM = 28
DROP_AREA_MIN_HEIGHT = 220

WINDOW_MIN_WIDTH = 720
WINDOW_MIN_HEIGHT = 520
PANEL_DEFAULT_WIDTH = 260
PANEL_MIN_WIDTH = 220
